//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfMarathon.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class HowLong
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Speed { get; set; }
        public string Length { get; set; }
        public string Image { get; set; }
    }
}
